#global
DEFAULT_WAIT_TIME_APP_LOAD = 2.0
DEFAULT_COMMAND_TIMEOUT = 10
DEFAULT_SCREENSHOT_NAME = "current_screen.png"

#mouse
DEFAULT_MOUSE_DURATION = 0.5
DEFAULT_DOUBLE_CLICK_INTERVAL = 0.1

# testing
# later from ai/json
TARGET_APP_NAME = 'Calculator'
CALC_BUTTON_X = 100
CALC_BUTTON_Y = 323