# Global settings
DEFAULT_COMMAND_TIMEOUT = 10
DEFAULT_SCREENSHOT_NAME = "current_screen.png"
DEFAULT_LAUNCHER_CHECK_TIMEOUT = 2
DEFAULT_APP_READY_TIMEOUT = 5
DEFAULT_APP_READY_CHECK_INTERVAL = 0.2

# Mouse settings
DEFAULT_MOUSE_DURATION = 0.5
DEFAULT_DOUBLE_CLICK_INTERVAL = 0.1

# Temporary test settings
TARGET_APP_NAME = "Calculator"
CALC_BUTTON_X = 100
CALC_BUTTON_Y = 323
